In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt



pd.options.mode.chained_assignment = None  #hide any pandas warnings

In [2]:
data = pd.read_csv('final-data.csv')
data.shape


(18, 4)

In [4]:
X = data.iloc[:, :-1].values
y = data.iloc[:, -1].values

In [5]:
from sklearn import svm

In [6]:
regr = svm.SVR()
regr.fit(X, y)

SVR()

In [7]:
regr.predict([[0.00,0.00,0.00]])

array([0.34778997])

In [8]:
regr.predict([[0.1,0.1,0.1]])

array([0.13001547])

In [9]:
regr.predict([[0.02,0.04,0.06]])

array([0.3496686])

In [10]:
regr.predict([[0.02,0.04,0.06]])

array([0.3496686])

In [11]:
regr.predict([[0.06,0.06,0.06]])

array([0.30032287])

In [12]:
regr.predict([[0.08,0.08,0.08]])

array([0.1797992])

In [13]:
regr.predict([[0.08,0.06,0.04]])

array([0.30587836])

In [14]:
regr.predict([[0.04,0.04,0.04]])

array([0.34758249])

In [15]:
regr.predict([[0.04,0.02,0.06]])

array([0.37357245])

In [16]:
regr.predict([[0.06,0.02,0.04]])

array([0.37244991])

In [17]:
regr.predict([[0.04,0.02,0.01]])

array([0.34961321])

In [18]:
regr.predict([[0.06,0.04,0.04]])

array([0.34604001])

In [19]:
regr.predict([[0.04,0.06,0.02]])

array([0.34107208])

In [21]:
regr.predict([[0.02,0.06,0.04]])

array([0.34485911])

In [22]:
regr.predict([[0.02,0.04,0.06]])

array([0.3496686])